### PR TITLE
Added es-la Latin American Keyboard Layout

### PR DESCRIPTION
**Pull request by Tato418**
I added latin american keyboard mapping, also implemented a "switch" to display correctly "|" char in this keyboard

### CODE REVIEW

**Review by ernesto-xload — APPROVED** [review]

**Comment by Tato418** [comment]
Sorry, on mobile the review icon is too close lol... The latam layout is complete, is necessary to check if other layouts can implement this too

**Comment by enricocirignaco** [comment]
Hi, I want to implement a Swiss German Layout. Where did you find the keyboard mapping for latin keyboard?

**Comment by Tato418** [comment]
> Hi, I want to implement a Swiss German Layout. Where did you find the keyboard mapping for latin keyboard?

Hi, I just basically compared https://es.m.wikipedia.org/wiki/Archivo:KB_Latin_American.svg, with https://upload.wikimedia.org/wikipedia/commons/5/51/KB_United_States-NoAltGr.svg and swap the ones that were incorrect in the ascii struct

**Comment by Tato418** [comment]
@ernesto-xload can you approve it?

**Review by Tato418 — COMMENTED** [review]
ok

**Comment by Tato418** [comment]
@ernesto-xload can you approve it?

**Pull request closed without merging**
